### ISSUE TITLE
Gib me CSS workload yo do thoughts

### ISSUE THREAD

**Issue by omkharche8** [robinroy03/homepage#1]

**Comment by robinroy03** [comment]
lmao sure

**Comment by omkharche8** [comment]
i liked this concept tho
I had written my script for Paul Graham essays
I had visualized a website where i do this
Same style

the name i thought was Rawm - (RAW OM)

**Comment by omkharche8** [comment]
Actually fuck it imma make it

**Comment by omkharche8** [comment]
I need 3 to 4 buttons on left side vertically aligned
Then right side is my content
Good
and the "<h2 tag" Stays the same

**Comment by robinroy03** [comment]
closing since a PR is merged.
